;=== English
LangString MAIN_App_Running 1033 "It appears that ${NAME} is already running."
LangString MAIN_Unable_Download 1033 "Unable to download file"
LangString MAIN_Not_Found 1033 "was not found. Please check your configuration"
LangString MAIN_No_Config 1033 "You need at least one ${CONFIGFILE} file on $EXEDIR\${DEFAULTCONFIGDIR}\ for a working VPN.  Please check your configuration"
LangString MAIN_Install_Tap 1033 "Install required virtual network drivers for ${NAME}?"
LangString MAIN_Install_Tap_Error 1033 "Error by installing virtual network drivers. Please start this app as a user with admin rights."
LangString MAIN_Uninstall_Tap 1033 "Uninstall ${NAME} virtual network drivers?"
LangString MAIN_Uninstall_Tap_Ok 1033 "${NAME} virtual network drivers were successfully uninstalled"
LangString MAIN_Uninstall_Tap_Error 1033 "Error by uninstalling virtual network drivers. Please start this app as a user with admin rights."